
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install SonarScanner
        run: |
           wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
           unzip sonar-scanner-cli-4.6.2.2472-linux.zip
           mv sonar-scanner-4.6.2.2472-linux sonar-scanner
           echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH


      - name: Run SonarQube Scan
        run: sonar-scanner -Dsonar.projectKey=iosdemo_code-smell -Dsonar.organization=iosdemo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9363ceb8b3189da6f03891a31b6b2a54cba433c1
