
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn clean install
      - name: quality scan using maven
        run: mvn sonar:sonar -Dsonar.projectKey=iosdemo_code-smell -Dsonar.organization=iosdemo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9363ceb8b3189da6f03891a31b6b2a54cba433c1
     
          
      
      
      - name: Run SonarQube Scan
        run: sonar-scanner -Dsonar.projectKey=iosdemo_code-smell -Dsonar.organization=iosdemo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9363ceb8b3189da6f03891a31b6b2a54cba433c1
